#! /bin/bash
function _docker () {
	_isRoot "exit"

	curl -sSL https://get.docker.com | sh || return 1
	setup_common || return 1

	#usermod -aG docker pi || return 1

	docker run hello-world || return 1

	cat >> /home/pi/.profile <<EOF

if [ -d "/saturn/docker/bin" ] ; then
    PATH='/saturn/docker/bin:$PATH'
fi
EOF
	return $?
}
