#! /bin/bash
function init_source_loop {
	for i in ${@}/* ; do
		if [[ -d $i ]] ; then
			init_source_loop $i
		elif [[ -f $i ]] ; then
			source $i
		fi
	done
}

init_source_loop /srv/common/functions
