#! /bin/bash
#-> RUN MAIN FUNCTIONS INIT
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source ${DIR}/functions/init

#-> CHECK FOR A PROJECT FUNCTIONS FOLDER TO RUN THROUGH THE LOADER
loader "${DIR}/project_functions/"

