#! /bin/bash
function system_primary_ip {
    # returns the primary IP assigned to eth0
    if ! ifconfig --version  ; then
      package install net-tools
    fi
    echo $(ifconfig eth0 | awk -F: '/inet addr:/ {print $2}' | awk '{ print $1 }')
}
